import { StyleSheet } from 'react-native';

export const C = {
  primary: '#7ea4d9',
  primaryDk: '#668fc9',
  primaryLt: '#e6eef8',
  green: '#10b981',
  greenLt: '#d1fae5',
  greenDk: '#065f46',
  amber: '#f59e0b',
  amberLt: '#fef3c7',
  red: '#ef4444',
  redLt: '#fee2e2',
  bg: '#edf1f5',
  white: '#ffffff',
  card: '#f7f9fc',
  border: '#d5dde7',
  borderLt: '#e8edf3',
  text: '#253241',
  textMd: '#3e5063',
  textSm: '#607388',
  textXs: '#8ea0b2',
};

export const styles = StyleSheet.create({
  splashContainer: { flex: 1, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center', padding: 20 },
  splashText: { color: C.white, fontSize: 16, fontWeight: 'bold', marginTop: 15 },
  
  // Auth Screen
  authContainer: { flexGrow: 1, backgroundColor: C.bg, justifyContent: 'center' },
  authHero: { backgroundColor: C.primary, padding: 40, alignItems: 'center', borderBottomLeftRadius: 30, borderBottomRightRadius: 30, shadowColor: C.primary, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 20, elevation: 10, marginBottom: -30, zIndex: 10 },
  authLogoCircle: { width: 80, height: 80, backgroundColor: C.white, borderRadius: 40, alignItems: 'center', justifyContent: 'center', marginBottom: 15, shadowColor: C.text, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 5 },
  authLogoEmoji: { fontSize: 40 },
  brandTitle: { fontSize: 28, fontWeight: '900', color: C.white, letterSpacing: 1 },
  brandSubtitle: { fontSize: 14, color: C.primaryLt, fontWeight: '600', marginTop: 5 },
  authCard: { backgroundColor: C.card, borderRadius: 24, padding: 24, marginHorizontal: 20, marginTop: 40, shadowColor: C.text, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 8, borderWidth: 1, borderColor: C.borderLt },
  authCardTitle: { fontSize: 22, fontWeight: '800', color: C.text, textAlign: 'center', marginBottom: 5 },
  authCardSubtitle: { fontSize: 13, color: C.textSm, textAlign: 'center', marginBottom: 25 },
  modeTabs: { flexDirection: 'row', backgroundColor: C.borderLt, borderRadius: 14, padding: 4, marginBottom: 20 },
  modeTabButton: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 10 },
  modeTabActive: { backgroundColor: C.card, shadowColor: C.text, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  modeTabText: { fontSize: 14, color: C.textSm, fontWeight: 'bold' },
  modeTabTextActive: { color: C.primary },
  inputGroup: { marginBottom: 16 },
  inputLabel: { fontSize: 13, fontWeight: 'bold', color: C.textMd, marginBottom: 6 },
  inputField: { height: 54, backgroundColor: C.bg, borderRadius: 14, paddingHorizontal: 16, borderWidth: 1, borderColor: C.border, fontSize: 16, color: C.text, fontWeight: '500' },
  authActionButton: { height: 56, backgroundColor: C.primary, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 10, shadowColor: C.primary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.25, shadowRadius: 16, elevation: 4 },
  authActionButtonText: { color: C.white, fontSize: 17, fontWeight: 'bold' },
  buttonDisabled: { backgroundColor: C.textXs, shadowOpacity: 0, elevation: 0 },
  forgotBtn: { alignItems: 'center', paddingVertical: 12, marginTop: 12 },
  forgotBtnText: { color: C.primary, fontWeight: 'bold', fontSize: 14 },
  forgotWrapper: { marginTop: 16, padding: 16, backgroundColor: C.bg, borderRadius: 16, borderWidth: 1, borderColor: C.border },
  forgotSubtitle: { fontSize: 12, color: C.textSm, lineHeight: 16, marginBottom: 12, fontWeight: '500' },
  forgotSubmitBtn: { backgroundColor: C.greenDk, padding: 12, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  forgotSubmitBtnText: { color: C.white, fontWeight: 'bold', fontSize: 14 },
  authFooterText: { textAlign: 'center', color: C.textXs, fontSize: 12, fontWeight: '600', marginTop: 30, marginBottom: 20 },

  // Main Layout
  mainContainer: { flex: 1, backgroundColor: C.bg },
  topHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 50, paddingBottom: 20, backgroundColor: C.primary, borderBottomLeftRadius: 24, borderBottomRightRadius: 24, shadowColor: C.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 8, zIndex: 10 },
  topHeaderLeft: { flex: 1 },
  topHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  appGreeting: { fontSize: 22, fontWeight: '900', color: C.white },
  condoIndicator: { fontSize: 13, color: C.primaryLt, fontWeight: '600', marginTop: 2 },
  ageBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 100 },
  ageAdultBg: { backgroundColor: C.green },
  ageRestrictedBg: { backgroundColor: C.amber },
  ageBadgeText: { fontSize: 11, fontWeight: 'bold', color: C.white },
  cartCountBadgeHeader: { backgroundColor: C.primaryDk, width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  cartCountBadgeHeaderIcon: { fontSize: 18 },
  cartCountDot: { position: 'absolute', top: -4, right: -4, backgroundColor: C.red, width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: C.primary },
  cartCountDotText: { color: C.white, fontSize: 10, fontWeight: '900' },
  tabContentArea: { flex: 1 },
  scrollPadding: { padding: 20, paddingBottom: 100 },
  
  // Cards & Wrappers
  cardWrapper: { backgroundColor: C.card, borderRadius: 24, padding: 20, shadowColor: C.text, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.05, shadowRadius: 15, elevation: 4, borderWidth: 1, borderColor: C.borderLt, marginBottom: 20 },
  cardHeaderTitle: { fontSize: 18, fontWeight: '900', color: C.text, marginBottom: 15, letterSpacing: -0.5 },

  // BLE Widget
  bleUnlockCard: { backgroundColor: C.green, borderRadius: 24, padding: 20, marginBottom: 20, shadowColor: C.green, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.25, shadowRadius: 15, elevation: 6 },
  bleDisabled: { backgroundColor: C.textXs, shadowOpacity: 0, elevation: 0 },
  bleUnlockLayout: { flexDirection: 'row', alignItems: 'center' },
  bleUnlockEmoji: { fontSize: 36, marginRight: 16 },
  bleUnlockTextCol: { flex: 1 },
  bleUnlockTitle: { fontSize: 18, fontWeight: '900', color: C.white, letterSpacing: 0.5 },
  bleUnlockSubtitle: { fontSize: 13, color: C.greenLt, fontWeight: 'bold', marginTop: 4 },

  // Cart empty state
  emptyCartBox: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 10 },
  emptyCartEmoji: { fontSize: 56, marginBottom: 16 },
  emptyCartTitle: { fontSize: 18, fontWeight: '800', color: C.textMd },
  emptyCartText: { fontSize: 14, color: C.textSm, textAlign: 'center', marginTop: 8, lineHeight: 20, fontWeight: '500' },
  emptyCartScanBtn: { backgroundColor: C.primary, paddingHorizontal: 24, paddingVertical: 14, borderRadius: 16, marginTop: 24, shadowColor: C.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4 },
  emptyCartScanBtnText: { color: C.white, fontWeight: 'bold', fontSize: 15 },

  // Cart Item
  cartListItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: C.borderLt },
  cartItemLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  cartProductIconBox: { width: 50, height: 50, backgroundColor: C.bg, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  cartProductIcon: { fontSize: 26 },
  cartProductTexts: { flex: 1 },
  cartProductName: { fontSize: 15, fontWeight: '800', color: C.text },
  cartProductDetails: { fontSize: 12, color: C.textSm, fontWeight: '600', marginTop: 4 },
  cartItemRight: { alignItems: 'flex-end', marginLeft: 10 },
  cartProductTotal: { fontSize: 15, fontWeight: '900', color: C.text, marginBottom: 8 },
  qtyControlRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.bg, borderRadius: 10, padding: 4 },
  qtyBtn: { width: 28, height: 28, backgroundColor: C.card, borderRadius: 8, alignItems: 'center', justifyContent: 'center', shadowColor: C.text, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 2, elevation: 2 },
  qtyBtnText: { fontSize: 16, fontWeight: '900', color: C.textMd },
  qtyTextVal: { fontSize: 14, fontWeight: '800', color: C.text, paddingHorizontal: 12 },

  // Summary & Pix
  summaryBox: { marginTop: 20, paddingTop: 20, borderTopWidth: 2, borderTopColor: C.borderLt },
  summaryLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  summaryLabel: { fontSize: 17, fontWeight: '800', color: C.textMd },
  summaryValue: { fontSize: 26, fontWeight: '900', color: C.primary },
  payBtnCheckout: { backgroundColor: C.green, borderRadius: 16, paddingVertical: 16, alignItems: 'center', justifyContent: 'center', shadowColor: C.green, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.2, shadowRadius: 12, elevation: 4 },
  payBtnCheckoutText: { color: C.white, fontSize: 17, fontWeight: 'bold' },
  pixResultBox: { backgroundColor: C.greenLt, borderColor: '#a7f3d0', borderWidth: 1, borderRadius: 24, padding: 20, marginBottom: 20 },
  pixResultHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, borderBottomWidth: 1, borderBottomColor: '#6ee7b7', paddingBottom: 12 },
  pixResultHeading: { color: C.greenDk, fontWeight: '900', fontSize: 15 },
  pixResultAmount: { color: C.greenDk, fontWeight: '800', fontSize: 15 },
  pixResultText: { fontSize: 13, color: C.greenDk, fontWeight: '600', marginBottom: 10 },
  pixCodeString: { backgroundColor: C.white, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#6ee7b7', fontFamily: 'monospace', fontSize: 12, color: C.greenDk, marginBottom: 16 },
  pixBtnRow: { flexDirection: 'row' },
  pixCopyBtn: { flex: 1, backgroundColor: C.greenDk, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  pixCopyBtnText: { color: C.white, fontWeight: 'bold', fontSize: 14 },
  pixStatusIndicator: { textAlign: 'center', fontSize: 12, fontWeight: '800', color: C.greenDk, marginTop: 14 },

  // Shortcuts
  quickShortcuts: { flexDirection: 'row', gap: 16 },
  shortcutBtn: { flex: 1, backgroundColor: C.card, borderRadius: 20, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: C.borderLt, shadowColor: C.text, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 10, elevation: 2 },
  shortcutEmoji: { fontSize: 28, marginBottom: 8 },
  shortcutText: { fontSize: 12, color: C.textMd, fontWeight: '800' },

  // Catalog
  fullCatalogContainer: { flex: 1, backgroundColor: C.bg },
  searchBarBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.card, borderWidth: 1, borderColor: C.border, borderRadius: 16, marginHorizontal: 20, marginTop: 20, paddingHorizontal: 16, shadowColor: C.text, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 8, elevation: 2 },
  searchBarField: { flex: 1, height: 54, color: C.text, fontWeight: '600', fontSize: 15 },
  clearSearchBtn: { padding: 8 },
  clearSearchBtnText: { color: C.textXs, fontSize: 16, fontWeight: 'bold' },
  categoriesScrollBox: { marginVertical: 16 },
  horizontalScrollPadding: { paddingHorizontal: 20 },
  categoryPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.card, borderWidth: 1, borderColor: C.border, borderRadius: 100, paddingHorizontal: 16, paddingVertical: 10, marginRight: 10, shadowColor: C.text, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.03, shadowRadius: 4, elevation: 1 },
  categoryPillActive: { backgroundColor: C.primary, borderColor: C.primary },
  categoryPillIcon: { fontSize: 16, marginRight: 8 },
  categoryPillText: { fontSize: 13, fontWeight: '800', color: C.textSm },
  categoryPillTextActive: { color: C.white },
  catalogGridPadding: { paddingHorizontal: 16, paddingBottom: 100 },
  emptySearchBox: { alignItems: 'center', paddingVertical: 60 },
  emptySearchEmoji: { fontSize: 56, marginBottom: 16 },
  emptySearchText: { color: C.textSm, fontSize: 15, fontWeight: 'bold' },
  catalogProductCard: { flex: 1, backgroundColor: C.card, borderRadius: 20, margin: 8, borderWidth: 1, borderColor: C.borderLt, shadowColor: C.text, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10, elevation: 2, overflow: 'hidden' },
  catalogCardImageContainer: { height: 120, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: C.borderLt },
  catalogCardImageEmoji: { fontSize: 56 },
  catalogCardDetails: { padding: 14 },
  catalogCardName: { fontSize: 14, fontWeight: '800', color: C.text, minHeight: 40 },
  catalogCardEan: { fontSize: 10, color: C.textXs, fontWeight: 'bold', marginTop: 4 },
  catalogCardBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
  catalogCardPrice: { fontSize: 15, fontWeight: '900', color: C.green },
  catalogCardAddBtn: { backgroundColor: C.primary, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 },
  catalogCardAddBtnText: { color: C.white, fontSize: 12, fontWeight: 'bold' },

  // Scanner
  scannerWrapper: { flex: 1, backgroundColor: '#000' },
  scannerStatusCard: { flex: 1, backgroundColor: C.text, alignItems: 'center', justifyContent: 'center', padding: 30 },
  scannerStatusText: { color: C.textXs, fontSize: 15, textAlign: 'center', marginTop: 20, lineHeight: 22, fontWeight: '600' },
  scannerErrorEmoji: { fontSize: 56, marginBottom: 15 },
  scannerErrorTitle: { fontSize: 20, fontWeight: 'bold', color: C.white, marginBottom: 6 },
  cameraFrame: { flex: 1, position: 'relative' },
  scannerMaskOuter: { position: 'absolute', inset: 0, justifyContent: 'space-between' },
  scannerMaskRow: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
  scannerMaskMiddleRow: { height: 260, flexDirection: 'row' },
  scannerMaskSide: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)' },
  scannerTargetArea: { width: 260, height: 260, borderWidth: 2, borderColor: 'transparent', position: 'relative' },
  scannerLaserLine: { height: 4, backgroundColor: C.red, position: 'absolute', left: 4, right: 4, opacity: 0.8, shadowColor: C.red, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 1, shadowRadius: 10 },
  cornerMarker: { position: 'absolute', width: 30, height: 30, borderColor: C.primary },
  topLeftCorner: { top: 0, left: 0, borderTopWidth: 6, borderLeftWidth: 6, borderTopLeftRadius: 12 },
  topRightCorner: { top: 0, right: 0, borderTopWidth: 6, borderRightWidth: 6, borderTopRightRadius: 12 },
  bottomLeftCorner: { bottom: 0, left: 0, borderBottomWidth: 6, borderLeftWidth: 6, borderBottomLeftRadius: 12 },
  bottomRightCorner: { bottom: 0, right: 0, borderBottomWidth: 6, borderRightWidth: 6, borderBottomRightRadius: 12 },
  scannerHintText: { color: C.white, fontSize: 15, fontWeight: '800', textAlign: 'center', backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, overflow: 'hidden' },
  scannerSimOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(15, 23, 42, 0.95)', paddingVertical: 20, paddingHorizontal: 15, borderTopLeftRadius: 24, borderTopRightRadius: 24 },
  scannerSimLabel: { color: C.textXs, fontSize: 11, fontWeight: 'bold', textAlign: 'center', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 1 },
  simScrollPadding: { paddingHorizontal: 5 },
  scannerSimBtn: { backgroundColor: C.textMd, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, marginRight: 10, borderWidth: 1, borderColor: C.textSm },
  scannerSimBtnText: { color: C.bg, fontSize: 12, fontWeight: 'bold' },

  // History
  emptyHistoryBox: { alignItems: 'center', paddingVertical: 50 },
  emptyHistoryEmoji: { fontSize: 56, marginBottom: 15 },
  emptyHistoryText: { color: C.textXs, fontSize: 14, fontWeight: '700' },
  historySubtitle: { fontSize: 13, color: C.textXs, fontWeight: 'bold', marginBottom: 20 },
  historyCardItem: { backgroundColor: C.bg, borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: C.border },
  historyCardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, borderBottomWidth: 1, borderBottomColor: C.borderLt, paddingBottom: 10 },
  historyCardId: { fontWeight: '900', color: C.text, fontSize: 14 },
  historyCardDate: { color: C.textSm, fontSize: 12, fontWeight: '700' },
  historyCardProducts: { marginBottom: 12 },
  historyProductLine: { fontSize: 13, color: C.textMd, marginVertical: 2, fontWeight: '600' },
  historyCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  historyTotalLabel: { fontSize: 13, color: C.textSm, fontWeight: 'bold' },
  historyTotalValue: { fontSize: 16, fontWeight: '900', color: C.green },

  // Profile
  profileDetailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: C.borderLt },
  profileLabel: { fontSize: 14, color: C.textSm, fontWeight: 'bold' },
  profileValue: { fontSize: 14, color: C.text, fontWeight: '900' },
  profileHelpCallout: { backgroundColor: '#e6eef8', borderColor: '#c4d5ea', borderWidth: 1, borderRadius: 20, padding: 20, marginTop: 24, marginBottom: 24 },
  profileCalloutTitle: { fontSize: 15, fontWeight: '900', color: C.primaryDk },
  profileCalloutText: { fontSize: 13, color: C.primaryDk, lineHeight: 18, marginTop: 6, fontWeight: '600' },
  profileCalloutBtn: { backgroundColor: C.primaryDk, borderRadius: 12, paddingVertical: 12, alignItems: 'center', marginTop: 16 },
  profileCalloutBtnText: { color: C.white, fontWeight: 'bold', fontSize: 13 },
  logoutAppBtn: { borderWidth: 1, borderColor: C.redLt, backgroundColor: '#fff5f5', borderRadius: 16, paddingVertical: 16, alignItems: 'center', justifyContent: 'center' },
  logoutAppBtnText: { color: C.red, fontSize: 15, fontWeight: 'bold' },

  // Modals
  successModalOverlay: { flex: 1, backgroundColor: 'rgba(15,23,42,0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  successModalCard: { backgroundColor: C.card, borderRadius: 32, padding: 30, width: '100%', maxWidth: 360, alignItems: 'center', shadowColor: C.green, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 30, elevation: 15 },
  successModalEmoji: { fontSize: 64, marginBottom: 16 },
  successModalTitle: { fontSize: 24, fontWeight: '900', color: C.green, textAlign: 'center' },
  successModalRecap: { backgroundColor: C.bg, borderWidth: 1, borderColor: C.border, borderRadius: 16, padding: 16, width: '100%', marginVertical: 20 },
  recapLine: { fontSize: 13, fontWeight: 'bold', color: C.textMd, marginVertical: 3 },
  successModalDescription: { fontSize: 13, color: C.textSm, textAlign: 'center', lineHeight: 20, fontWeight: '600' },
  successModalCloseBtn: { backgroundColor: C.green, borderRadius: 16, width: '100%', paddingVertical: 16, alignItems: 'center', marginTop: 24 },
  successModalCloseBtnText: { color: C.white, fontWeight: 'bold', fontSize: 15 },

  // Bottom Tab Bar
  bottomTabBar: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 75, backgroundColor: C.card, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: C.borderLt, paddingHorizontal: 20, paddingBottom: 10 },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', height: '100%' },
  tabItemActive: { opacity: 1 },
  tabIcon: { fontSize: 24 },
  tabLabel: { fontSize: 11, color: C.textXs, fontWeight: '800', marginTop: 4 },
  tabLabelActive: { color: C.primary },
  floatingScannerBtn: { width: 68, height: 68, borderRadius: 34, backgroundColor: C.card, justifyContent: 'center', alignItems: 'center', top: -20, shadowColor: C.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.25, shadowRadius: 12, elevation: 8 },
  innerFloatingScanner: { width: 56, height: 56, borderRadius: 28, backgroundColor: C.primary, justifyContent: 'center', alignItems: 'center' },
  floatingScannerIcon: { fontSize: 26, color: C.white },
});
